/**
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. OpenMRS is also distributed under
 * the terms of the Healthcare Disclaimer located at http://openmrs.org/license.
 *
 * Copyright (C) OpenMRS Inc. OpenMRS is a registered trademark and the OpenMRS
 * graphic logo is a trademark of OpenMRS Inc.
 */
package org.openmrs.module.reporting.report.service.db;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.hibernate.query.Query;
import org.openmrs.api.db.DAOException;
import org.openmrs.api.db.hibernate.DbSessionFactory;
import org.openmrs.module.reporting.report.ReportDesign;
import org.openmrs.module.reporting.report.ReportProcessorConfiguration;
import org.openmrs.module.reporting.report.ReportRequest;
import org.openmrs.module.reporting.report.ReportRequest.Status;
import org.openmrs.module.reporting.report.definition.ReportDefinition;
import org.openmrs.module.reporting.report.renderer.ReportRenderer;

import java.util.Date;
import java.util.List;

/**
 * ReportService Database Access Interface
 */
public class HibernateReportDAO implements ReportDAO {
	
	protected final Log log = LogFactory.getLog(getClass());
	
	//***** PROPERTIES *****
	private DbSessionFactory sessionFactory;
	
	//***** INSTANCE METHODS *****
	
	//****** REPORT DESIGNS *****
	
	/**
	 * @param uuid
	 * @return the ReportDesign with the given uuid
	 */
	public ReportDesign getReportDesignByUuid(String uuid) throws DAOException {
		Query q = sessionFactory.getCurrentSession().createQuery("from ReportDesign r where r.uuid = :uuid");
		return (ReportDesign) q.setParameter("uuid", uuid).uniqueResult();
	}
	
	/**
	 * Get the {@link ReportDesign} with the given id
	 * @param id The Integer ReportDesign id
	 * @return the matching {@link ReportDesign} object
	 * @throws DAOException
	 */
	public ReportDesign getReportDesign(Integer id) throws DAOException {
		return (ReportDesign) sessionFactory.getCurrentSession().get(ReportDesign.class, id);
	}
		
	/**
	 * Return a list of {@link ReportDesign}s for the passed {@link ReportDefinition} and {@link ReportRenderer} class,
	 * optionally including those that are retired
	 * @param includeRetired if true, indicates that retired {@link ReportDesign}s should also be included
	 * @return a List<ReportDesign> object containing all of the {@link ReportDesign}s
	 * @throws DAOException
	 */
	@SuppressWarnings("unchecked")
	public List<ReportDesign> getReportDesigns(ReportDefinition reportDefinition, Class<? extends ReportRenderer> rendererType, 
											   boolean includeRetired) throws DAOException {
		StringBuilder hql = new StringBuilder("from ReportDesign r where 1 = 1");
		if (reportDefinition != null) {
			hql.append(" and r.reportDefinition = :reportDefinition");
		}
		if (rendererType != null) {
			hql.append(" and r.rendererType = :rendererType");
		}
		if (includeRetired == false) {
			hql.append(" and r.retired = false");
		}
		Query q = sessionFactory.getCurrentSession().createQuery(hql.toString());
		if (reportDefinition != null) {
			q.setParameter("reportDefinition", reportDefinition);
		}
		if (rendererType != null) {
			q.setParameter("rendererType", rendererType);
		}
		return q.list();
	}
	
	/**
	 * Save or update the given <code>ReportDesign</code> in the database. If this is a new
	 * ReportDesign, the returned ReportDesign will have a new
	 * {@link ReportDesign#getId()} inserted into it that was generated by the database
	 * 
	 * @param reportDesign The <code>ReportDesign</code> to save or update
	 * @throws DAOException
	 */
	public ReportDesign saveReportDesign(ReportDesign reportDesign) throws DAOException {
		sessionFactory.getCurrentSession().saveOrUpdate(reportDesign);
		return reportDesign;
	}
	
	/**
	 * Purges a <code>ReportDesign</code> from the database.
	 * @param reportDesign The <code>ReportDesign</code> to remove from the system
	 * @throws DAOException
	 */
	public void purgeReportDesign(ReportDesign reportDesign) {
		sessionFactory.getCurrentSession().delete(reportDesign);
	}
	
	//****** REPORT PROCESSOR CONFIGURATIONS *****
	
	/**
	 * Saves a {@link ReportProcessorConfiguration} to the database and returns it
	 */
	public ReportProcessorConfiguration saveReportProcessorConfiguration(ReportProcessorConfiguration processorConfiguration) {
		sessionFactory.getCurrentSession().saveOrUpdate(processorConfiguration);
		return processorConfiguration;
	}

	/**
	 * @return the {@link ReportProcessorConfiguration} with the passed id
	 */
	public ReportProcessorConfiguration getReportProcessorConfiguration(Integer id) {
		return (ReportProcessorConfiguration) sessionFactory.getCurrentSession().get(ReportProcessorConfiguration.class, id);
	}

	/**
	 * @return the {@link ReportProcessorConfiguration} with the passed uuid
	 */
	public ReportProcessorConfiguration getReportProcessorConfigurationByUuid(String uuid) {
		Query q = sessionFactory.getCurrentSession().createQuery("from ReportProcessorConfiguration r where r.uuid = :uuid");
		return (ReportProcessorConfiguration) q.setParameter("uuid", uuid).uniqueResult();
	}
	
	/**
	 * @return all the {@link ReportProcessorConfiguration}s
	 */
	@SuppressWarnings("unchecked")
	public List<ReportProcessorConfiguration> getAllReportProcessorConfigurations(boolean includeRetired) {
		String hql = "from ReportProcessorConfiguration r" + (includeRetired ? "" : " where r.retired = false");
		return sessionFactory.getCurrentSession().createQuery(hql).list();
	}
	
	/**
	 * @return all the {@link ReportProcessorConfiguration}s that are meant to be applied globally, i.e., their reportDesign property is null
	 */
	@SuppressWarnings("unchecked")
	public List<ReportProcessorConfiguration> getGlobalReportProcessorConfigurations() {
		String hql = "from ReportProcessorConfiguration r where r.retired = false and r.reportDesign is null";
		return sessionFactory.getCurrentSession().createQuery(hql).list();
	}
	
	/**
	 * Deletes the passed {@link ReportProcessorConfiguration}
	 */
	public void purgeReportProcessorConfiguration(ReportProcessorConfiguration processorConfiguration) {
		sessionFactory.getCurrentSession().delete(processorConfiguration);
	}
	
	//****** REPORT REQUESTS *****
	
	/**
	 * @see ReportDAO#saveReportRequest(ReportRequest)
	 */
	public ReportRequest saveReportRequest(ReportRequest request) {
		sessionFactory.getCurrentSession().saveOrUpdate(request);
		return request;
	}

	/**
	 * @see ReportDAO#getReportRequest(java.lang.Integer)
	 */
	public ReportRequest getReportRequest(Integer id) {
		return (ReportRequest) sessionFactory.getCurrentSession().get(ReportRequest.class, id);
	}

	/**
	 * @see ReportDAO#getReportRequestByUuid(java.lang.String)
	 */
	public ReportRequest getReportRequestByUuid(String uuid) {
		Query q = sessionFactory.getCurrentSession().createQuery("from ReportRequest r where r.uuid = :uuid");
		return (ReportRequest) q.setParameter("uuid", uuid).uniqueResult();
	}

	/**
	 * @see ReportDAO#getReportRequests(ReportDefinition, Date, Date, Integer, Integer, Status...)
	 */
	@SuppressWarnings("unchecked")
	public List<ReportRequest> getReportRequests(ReportDefinition reportDefinition, Date requestOnOrAfter, Date requestOnOrBefore, Integer firstResult, Integer maxResults, Status...statuses) {
		final Query query = createReportRequestsBaseQuery(
				"from ReportRequest r",
				reportDefinition,
				requestOnOrAfter,
				requestOnOrBefore,
				statuses);
		query.setComment("ReportRequest list");

		if (firstResult != null) {
			query.setFirstResult(firstResult);
		}

		if(maxResults != null) {
			query.setMaxResults(maxResults);
		}

		return query.list();
	}

	@Override
	public long getReportRequestsCount(ReportDefinition reportDefinition, Date requestOnOrAfter, Date requestOnOrBefore, Status... statuses) {
		final Query query = createReportRequestsBaseQuery(
				"select count(r) from ReportRequest r",
				reportDefinition,
				requestOnOrAfter,
				requestOnOrBefore,
				statuses);
		return ((Number) query.uniqueResult()).longValue();
	}

	/**
	 * @see ReportDAO#purgeReportRequest(ReportRequest)
	 */
	public void purgeReportRequest(ReportRequest request) {
		sessionFactory.getCurrentSession().delete(request);
	}

	/**
	 * @see ReportDAO#purgeReportRequestsForReportDefinition(String)
	 */
	@Override
	public void purgeReportRequestsForReportDefinition(String reportDefinitionUuid) {
		String hql = "delete from ReportRequest r where r.reportDefinition.definition=:uuid";
		Query query = sessionFactory.getCurrentSession().createQuery(hql);
		query.setParameter("uuid", reportDefinitionUuid);
		query.executeUpdate();
	}


	/**
	 * @see ReportDAO#purgeReportDesignsForReportDefinition(String)
	 */
	@Override
	public void purgeReportDesignsForReportDefinition(String reportDefinitionUuid) {
		String hql = "delete from ReportDesign r where r.reportDefinition=:uuid";
		Query query = sessionFactory.getCurrentSession().createQuery(hql);
		query.setParameter("uuid", reportDefinitionUuid);
		query.executeUpdate();
	}

	/**
	 * @see ReportDAO#getReportRequestUuids(String)
	 */
	@Override
	public List<String> getReportRequestUuids(String reportDefinitionUuid) {
		String hql = "select uuid from ReportRequest r where r.reportDefinition.definition=:uuid";
		Query query = sessionFactory.getCurrentSession().createQuery(hql);
		query.setParameter("uuid", reportDefinitionUuid);
		return query.list();
	}

	//***** PROPERTY ACCESS *****

	/**
	 * @return the sessionFactory
	 */
	public DbSessionFactory getSessionFactory() {
		return sessionFactory;
	}

	/**
	 * @param sessionFactory the sessionFactory to set
	 */
	public void setSessionFactory(DbSessionFactory sessionFactory) {
		this.sessionFactory = sessionFactory;
	}

	private Query createReportRequestsBaseQuery(String select, ReportDefinition reportDefinition, Date requestOnOrAfter, Date requestOnOrBefore, Status... statuses) {
		StringBuilder hql = new StringBuilder(select).append(" where 1 = 1");
		if (reportDefinition != null) {
			hql.append(" and r.reportDefinition.definition = :reportDefinitionUuid");
		}
		if (requestOnOrAfter != null) {
			hql.append(" and r.requestDate >= :requestOnOrAfter");
		}
		if (requestOnOrBefore != null) {
			hql.append(" and r.requestDate <= :requestOnOrBefore");
		}
		if (statuses != null && statuses.length > 0) {
			hql.append(" and r.status in (:statuses)");
		}
		if (select.startsWith("from ")) {
			hql.append(" order by r.requestDate desc, r.evaluateStartDatetime desc, r.evaluateCompleteDatetime desc, r.priority desc");
		}
		Query query = sessionFactory.getCurrentSession().createQuery(hql.toString());
		if (reportDefinition != null) {
			query.setParameter("reportDefinitionUuid", reportDefinition.getUuid());
		}
		if (requestOnOrAfter != null) {
			query.setParameter("requestOnOrAfter", requestOnOrAfter);
		}
		if (requestOnOrBefore != null) {
			query.setParameter("requestOnOrBefore", requestOnOrBefore);
		}
		if (statuses != null && statuses.length > 0) {
			query.setParameterList("statuses", statuses);
		}
		return query;
	}
}
