#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

required_classes=(
  "addresshierarchy:AddressHierarchyAjaxController"
  "appointments:AppointmentController"
  "appointments:AppointmentServiceAttributeTypeController"
  "appointments:AppointmentServiceController"
  "appointments:AppointmentServicesController"
  "appointments:AppointmentsController"
  "appointments:RecurringAppointmentsController"
  "appointments:SpecialityController"
  "appointments:AdhocTeleconsultationController"
  "billing:BillResource"
  "billing:BillLineItemResource"
  "billing:BillableServiceResource"
  "billing:BillDiscountResource"
  "billing:BillExemptionResource"
  "billing:BillExemptionRuleResource"
  "billing:BillRefundResource"
  "billing:CashierItemPriceResource"
  "billing:CashPointResource"
  "billing:PaymentAttributeResource"
  "billing:PaymentModeAttributeTypeResource"
  "billing:PaymentModeResource"
  "billing:PaymentResource"
  "billing:TimesheetResource"
  "billing:ReceiptController"
  "billing:CashierRestController"
  "billing:CashierResourceController"
  "billing:CashierResourceControllerV2"
  "billing:CashierSubResourceController"
  "cohort:CohortAttributeResource"
  "cohort:CohortAttributeTypeResource"
  "cohort:CohortMainRestController"
  "cohort:CohortMemberAttributeResource"
  "cohort:CohortMemberAttributeTypeResource"
  "cohort:CohortMemberResource"
  "cohort:CohortResource"
  "cohort:CohortTypeResource"
  "emrapi:ActiveVisitController"
  "emrapi:DiagnosisController"
  "emrapi:EmrApiConfigurationController"
  "emrapi:EmrConceptSearchController"
  "emrapi:EmrEncounterController"
  "emrapi:InpatientAdmissionController"
  "emrapi:InpatientRequestController"
  "emrapi:InpatientVisitsController"
  "emrapi:LocationThatSupportsVisitsController"
  "emrapi:MothersAndChildrenController"
  "emrapi:VisitController"
  "fua:FuaController"
  "fua:FuaEstadoController"
  "fua:FuaRedirectionController"
  "idgen:IdgenRestController"
  "idgen:IdgenSubResourceRestController"
  "imaging:DicomStudyController"
  "imaging:ImagingResourceController"
  "imaging:RequestProcedureController"
  "legacyui:CustomValueController"
  "legacyui:Hl7InArchiveListController"
  "legacyui:Hl7InErrorListController"
  "legacyui:Hl7InQueueListController"
  "legacyui:LocalizationController"
  "legacyui:LocationQueryController"
  "legacyui:ModuleManagementController"
  "legacyui:SearchIndexController"
  "legacyui:VisitListController"
  "metadatamapping:MetadataMappingRestController"
  "metadatamapping:MetadataMappingRestSubController"
  "metadatamapping:MetadataSetMemberResource"
  "metadatamapping:MetadataSetResource"
  "metadatamapping:MetadataSourceResource"
  "metadatamapping:MetadataTermMappingResource"
  "o3forms:O3FormsResourceController"
  "openconceptlab:OpenConceptLabRestController"
  "openconceptlab:OpenConceptLabRestSubController"
  "openconceptlab:ImportActionResource"
  "openconceptlab:ImportResource"
  "openconceptlab:ItemResource"
  "openconceptlab:SubscriptionResource"
  "ordertemplates:OrderTemplatesResource"
  "ordertemplates:OrderTemplatesRestController"
  "patientdocuments:EncounterDataPdfExportController"
  "patientdocuments:PatientIdStickerDataPdfExportController"
  "patientdocuments:BasePatientIdStickerModuleController"
  "patientflags:PatientFlagsRestController"
  "patientflags:PatientFlagDisplayPointResource"
  "patientflags:PatientFlagFlagResource"
  "patientflags:PatientFlagPriorityResource"
  "patientflags:PatientFlagResource"
  "patientflags:PatientFlagTagResource"
  "queue:Legacy1xRestController"
  "queue:QueueEntryMetricRestController"
  "queue:QueueEntryTransitionRestController"
  "queue:QueueEntryResource"
  "queue:QueueEntrySubResource"
  "queue:QueueResource"
  "queue:QueueRoomResource"
  "queue:RoomProviderMapResource"
  "reporting:ManageDatasetsController"
  "reportingrest:AdHocDataSetResource"
  "reportingrest:AdHocQueryResource"
  "reportingrest:BaseDefinitionResource"
  "reportingrest:CohortDefinitionResource"
  "reportingrest:DataSetDefinitionResource"
  "reportingrest:DefinitionLibraryResource"
  "reportingrest:EvaluatedCohortResource"
  "reportingrest:EvaluatedDataSetResource"
  "reportingrest:EvaluatedReportDefinitionResource"
  "reportingrest:EvaluatedResource"
  "reportingrest:ReportDefinitionResource"
  "reportingrest:ReportDefinitionsWithScheduledRequestsResource"
  "reportingrest:ReportDesignResource"
  "reportingrest:ReportingRestController"
  "reportingrest:ReportRequestResource"
  "sihsalusinterop:DyakuSubmissionController"
  "sihsalusinterop:InteropQueueController"
  "stockmanagement:BatchJobArtifactController"
  "stockmanagement:BatchJobOwnerResource"
  "stockmanagement:BatchJobResource"
  "stockmanagement:DispenseRequestResource"
  "stockmanagement:IndexRebuildController"
  "stockmanagement:LocationResource"
  "stockmanagement:LocationTreeSynchronizeController"
  "stockmanagement:OrderItemResource"
  "stockmanagement:PartyResource"
  "stockmanagement:PrivilegeScopeResource"
  "stockmanagement:ReportResource"
  "stockmanagement:SessionController"
  "stockmanagement:StockBatchResource"
  "stockmanagement:StockItemImportController"
  "stockmanagement:StockItemInventoryResource"
  "stockmanagement:StockItemPackagingUOMResource"
  "stockmanagement:StockItemReferenceResource"
  "stockmanagement:StockItemResource"
  "stockmanagement:StockItemTransactionResource"
  "stockmanagement:StockManagementResourceController"
  "stockmanagement:StockOperationActionLineItemResource"
  "stockmanagement:StockOperationActionResource"
  "stockmanagement:StockOperationBatchNumbersResource"
  "stockmanagement:StockOperationItemCostResource"
  "stockmanagement:StockOperationItemResource"
  "stockmanagement:StockOperationLinkResource"
  "stockmanagement:StockOperationResource"
  "stockmanagement:StockOperationTypeLocationScopeResource"
  "stockmanagement:StockOperationTypeResource"
  "stockmanagement:StockRuleResource"
  "stockmanagement:StockSourceResource"
  "stockmanagement:SubResourceBase"
  "stockmanagement:UserRoleScopeLocationResource"
  "stockmanagement:UserRoleScopeOperationTypeResource"
  "stockmanagement:UserRoleScopeResource"
  "teleconsultation:TeleconsultationController"
)

missing=()
for required_class in "${required_classes[@]}"; do
  module="${required_class%%:*}"
  class_name="${required_class#*:}"
  module_sources="modules/$module/src/main/java"
  if [[ ! -d "$module_sources" ]]; then
    missing+=("$module:$class_name (missing module sources)")
    continue
  fi
  if ! rg -q "(class|interface|enum|@interface)[[:space:]]+$class_name\\b" "$module_sources"; then
    missing+=("$module:$class_name")
  fi
done

if (( ${#missing[@]} > 0 )); then
  echo "Missing REST surface classes:"
  printf '  - %s\n' "${missing[@]}"
  exit 1
fi

echo "REST surface check covers ${#required_classes[@]} expected controllers/resources."
